### PR TITLE
MAISTRA-1958 Support JSON values in annotation k8s.v1.cni.cncf.io/networks

### PR DESCRIPTION
**Pull request by luksa**

### CODE REVIEW

**Comment by luksa** [comment]
/hold

This is scheduled to go into 2.0.1

**Review by dgn — APPROVED** [review]

**Review by jwendell — APPROVED** [review]

**Comment by jwendell** [comment]
@luksa Did you upstream this?

**Comment by luksa** [comment]
@jwendell Yes.

**Pull request merged**
