### PR TITLE
OSSM-2049: Fix handling Endpoints and ServiceAccounts in federation controller

### PR DESCRIPTION
**Pull request by jewertow**

### CODE REVIEW

**Review by luksa — APPROVED** [review]

**Comment by luksa** [comment]
Note: The unit test fails only because of the xns-informers' `HasSynced()` bug.

**Comment by luksa** [comment]
@jwendell our CI jobs are misconfigured... it says the rerun command is `/test unit`, but it should say `/test istio-unit`

EDIT: oh, it's more complicated than that. openshift-ci wants `/test istio-unit`, whereas @maistra-bot wants `/test unit`. Whatever you type, one of them complains.

**Review by dgn — APPROVED** [review]

**Pull request merged**
