### PR TITLE
MAISTRA-2150: Prevent deadlock, do not hold edsClusterMutex when load…

### PR DESCRIPTION
**Pull request by knrc**
…ing assignments

### CODE REVIEW

**Review by brian-avery — APPROVED** [review]

**Review by jwendell — COMMENTED** [review]
I'm confused. Here you're touching `edsz` function, but in the Jira you mix calls with `cdsz`. Is that right?

**Comment by knrc** [comment]
> I'm confused. Here you're touching `edsz` function, but in the Jira you mix calls with `cdsz`. Is that right?

In the reproducer?  Yes, it's a simple invocation which demonstrates the deadlock within pilot.

**Comment by jwendell** [comment]
> > I'm confused. Here you're touching `edsz` function, but in the Jira you mix calls with `cdsz`. Is that right?
> 
> In the reproducer? Yes, it's a simple invocation which demonstrates the deadlock within pilot.

How? They use different mutexes.

**Comment by knrc** [comment]
> How? They use different mutexes.

It's a cascade, it goes deeper.  I'll add details in the JIRA.

**Comment by knrc** [comment]
> It's a cascade, it goes deeper. I'll add details in the JIRA.

The explanation is in the JIRA, deadlock on edsClusterMutex cascades to adsClientsMutex

**Review by jwendell — APPROVED** [review]
Thanks for the clarification.

**Comment by knrc** [comment]
> Thanks for the clarification.

No problem at all, your question prompted me to add in the details which would be necessary to understand the impact.  I should have done this before.

**Pull request merged**
