### PR TITLE
[samples] Update bookinfo images for 2.4

### PR DESCRIPTION
**Pull request by bartoszmajsak**
update/rebuild maistra bookinfo images for 2.3 #505. remove runasuser from deployments #396.
add sidecar injection annotations #402.

use maistra org images

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
@jwendell should we update images to `2.4.0`? If so - where should I send a PR to?

**Comment by jwendell** [comment]
> @jwendell should we update images to `2.4.0`? If so - where should I send a PR to?

I think we are fine with 2.3. We don't have 2.4 images yet.

Plus, can we have a single PR for all stuff under `samples`? For instance, can we move the changes in this PR https://github.com/maistra/istio/pull/695  into a commit here?

And this:
62ba2fef5f | ([misc] MAISTRA-2355: Change httpbin port to 8000 (#340), 2021-05-13)

**Comment by bartoszmajsak** [comment]
@jwendell should we squash them all to one under this PR or keep them as is?

**Review by jwendell — APPROVED** [review]
I'd prefer squash everything together

**Pull request merged**
