### PR TITLE
ignore me

### PR DESCRIPTION
**Pull request by jwendell**

### CODE REVIEW

**Comment by yxun** [comment]
@jwendell 
For comparison, when I change the tag from 2.3 to 2.2 , the api 2.3 job passed.
https://github.com/openshift/release/pull/32705

nvm, I see the istio 2.3 job passed here as well. must be something else caused the git issue before.

**Comment by jwendell** [comment]
> nvm, I see the istio 2.3 job passed here as well. must be something else caused the git issue before.

It did not pass. I'm changing the test to debug the issue.

**Pull request closed without merging**
