### PR TITLE
OSSM-303 | Add routeConfig property to istio-ingress helm values

### PR DESCRIPTION
**Pull request by jewertow**
This change is related to this [pull request](https://github.com/maistra/istio-operator/pull/884) to Istio Operator.

### CODE REVIEW

**Comment by jwendell** [comment]
Build is failing because proxy artifact was deleted from gcs :/

**Review by dgn — APPROVED** [review]

**Comment by dgn** [comment]
strange failure... 
/retest

**Comment by jewertow** [comment]
I'm trying to fix failing image: #470

**Comment by jwendell** [comment]
To fix the linter issue, add `quay.io` into `common/config/.hadolint.yml`. This is a generated file, but it's unlikely that it's going to change since upstream 1.9 branch is dead, therefore it will not receive any update.

**Pull request merged**
