### PR TITLE
MAISTRA-1642: Add support for proxy env annotation

### PR DESCRIPTION
**Pull request by knrc**

### CODE REVIEW

**Review by jwendell — APPROVED** [review]

**Comment by jwendell** [comment]
@dgn do you know of any issues with kind (too old kind?) on 1.1 image? See this failure for example. Never seen this before though.

**Comment by knrc** [comment]
@jwendell There is at least one issue covering broken kind integration within maistra, for the integration tests.

**Comment by knrc** [comment]
@jwendell https://issues.redhat.com/browse/MAISTRA-1301.

**Comment by jwendell** [comment]
This is an attempt to fix it: https://github.com/maistra/test-infra/pull/60

**Comment by jwendell** [comment]
ok, so, it never worked, right? I thought we had a regression here.

**Comment by knrc** [comment]
@jwendell The issue has certainly been known about for a few months

**Review by brian-avery — APPROVED** [review]

**Pull request merged**
