### PR TITLE
MAISTRA-774: Update certificates for testing

### PR DESCRIPTION
**Pull request by knrc**

### CODE REVIEW

**Comment by dgn** [comment]
This seems to be missing the updates to `root.cert` and `root.key`, upstream re-generated those as well.

**Review by dgn — CHANGES_REQUESTED** [review]
`root.cert` and `.key` missing

**Comment by knrc** [comment]
Sorry, I thought it was a single commit.  @dgn thanks for raising this.

**Comment by knrc** [comment]
@dgn Sorry, should be fixed now

**Comment by knrc** [comment]
This fixes broken tests, I'm going to merge this by hand

**Review by dgn — APPROVED** [review]

**Pull request merged**
