### PR TITLE
MAISTRA-2051: Add xns-informer for Service APIs

### PR DESCRIPTION
**Pull request by bison**
This enables multi-namespace aware informers for the optional Kubernetes Service APIs.

### CODE REVIEW

**Review by brian-avery — APPROVED** [review]

**Comment by bison** [comment]
/test integration

Integration tests seem stuck...

**Comment by brian-avery** [comment]
The integration tests are running now but for some reason the Git status checks aren't reflecting that. Will see how they turn out.

**Comment by bison** [comment]
Turns out the integration tests were just taking a really long time to fail because I had forgotten to add the service-apis to the scheme, and lists were failing and being retried a lot. Fixed.

**Pull request merged**
