### PR TITLE
OSSM-1724 Update to 1.12.9

### PR DESCRIPTION
**Pull request by dgn**

### CODE REVIEW

**Comment by jwendell** [comment]
I think you need to run `make gen` (or `go mod vendor`)

**Comment by dgn** [comment]
> I think you need to run `make gen` (or `go mod vendor`)

Yup.. I'm on the move and don't have enough bandwidth to run `make gen` here, because of the container pull :D Will update later

**Review by jwendell — APPROVED** [review]

**Review by jewertow — APPROVED** [review]

**Pull request merged**
