### PR TITLE
Fix dnf update issue

### PR DESCRIPTION
**Pull request by luksa**
This fixes the following issue:

Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist

### CODE REVIEW

**Review by jwendell — APPROVED** [review]
🤷🏻

Feel free to `/override <test-name>` the failing tests

**Comment by luksa** [comment]
/override integ-security-2-5 integ-servicemesh-2-5 maistra-istio-unit-2-5

**Comment by luksa** [comment]
/override ci/prow/integ-security-2-5 ci/prow/integ-servicemesh-2-5 ci/prow/maistra-istio-unit-2-5

**Pull request merged**
