### PR TITLE
MAISTRA-2051: Update xns-informers to latest

### PR DESCRIPTION
**Pull request by bison**
This updates xns-informers to the latest version. The Kubernetes client was reset to the version in `release-1.8` then only the necessary changes reapplied. The previously broken tests (now fixed) are no longer marked as skipped.

### CODE REVIEW

**Review by brian-avery — APPROVED** [review]

**Review by dgn — APPROVED** [review]

**Comment by bison** [comment]
/test integration

😱

**Comment by dgn** [comment]
we might have to skip that test.

**Comment by jwendell** [comment]
Is it always failing on this test?

**Comment by bison** [comment]
> Is it always failing on this test?

Today, yes it's always failing on `TestDashboard`. Passed fine on Friday.

**Comment by bison** [comment]
I marked it as skipped for now. Will make a note to come back to it.

**Pull request merged**
