### PR TITLE
OSSM-728 Configuration scripts for Federation on Z and P, and bare metal

### PR DESCRIPTION
**Pull request by dgn**
Let's finally merge the config examples created by @cfilleke. This also moves our federation examples to the `./samples` directory where they belong.

### CODE REVIEW

**Comment by jwendell** [comment]
Worth to wait for 2.4?

**Comment by dgn** [comment]
> Worth to wait for 2.4?

Why wait? It's just example config, no user impact

**Comment by jwendell** [comment]
> > Worth to wait for 2.4?
> 
> Why wait? It's just example config, no user impact

One less commit to cherry-pick to 2.4 :) But I don't have a strong opinion. I'm fine either way.

**Review by jewertow — APPROVED** [review]

**Comment by dgn** [comment]
btw I double-checked with QE to make sure nobody's referencing these scripts. I don't want to break anyone by moving them around

**Pull request merged**
