### PR TITLE
MAISTRA-1755 invoke UpdateNamespaces() as part of MemberRollControlle…

### PR DESCRIPTION
**Pull request by rcernich**
…r.Register()

Signed-off-by: rcernich <rcernich@redhat.com>

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Review by knrc — APPROVED** [review]

**Comment by rcernich** [comment]
This is the last PR required to get a working 2.0 install

**Review by dgn — APPROVED** [review]

**Pull request merged**
