### PR TITLE
MAISTRA-2051: Run sidecars with dynamically-determined user IDs

### PR DESCRIPTION
**Pull request by brian-avery**
A lot of this code was refactored in 1.8. This takes Marko's original PR and rewrites it to work with the refactor. 

Squashed commit, incorporates changes from:

  * MAISTRA-551 Run sidecar with a dynamically-determined runAsUser ID

  * MAISTRA-611 Partial injection of just the annotation and runAsUser id

  * MAISTRA-668 Fix expected output of webhook injection

  The sidecar injector now sets the securityContext.runAsUser field
  regardless if it is specified in the sidecar template or not. This is
  to allow the sidecar template to not include the field, which is
  required to ensure that istioctl kube-inject outputs manifests that
  pass the SCC admission controller (if the runAsUser is specified, the
  SCC controller will reject the pod, as the uid won't be in the proper
  range). The sidecar injector then injects the correct runAsUser id even
  if it isn't specified in the template.

### CODE REVIEW

**Review by luksa — APPROVED** [review]

**Comment by bison** [comment]
Do you mind squashing the commits and adding a `MAISTRA-2051:` prefix? It will make going through the git logs during the next rebase a lot easier.

**Comment by brian-avery** [comment]
Sure. I can do that. Was thinking about that in the meeting. Not sure how this will show up in commit history.

**Comment by bison** [comment]
So, it looks like it ended up with my last commit to this branch in the commit message somehow, and still doesn't have the prefix in the summary line. Not sure what happened.

**Comment by bison** [comment]
Yeah, this ended up pulling the the commits from #229. Probably needed a rebase.

**Pull request merged**
