### PR TITLE
[maistra-2.6] fix TestReadSignedCertificate

### PR DESCRIPTION
**Pull request by jewertow**

### CODE REVIEW

**Review by jwendell — COMMENTED** [review]
Isn't this already in 1.20? We just need to merge latest 1.20 changes into 2.6?
https://github.com/istio/istio/pull/51053

**Comment by jewertow** [comment]
Yes, it is, but we would have to merge release-1.20, because that commit is not included in any tag yet.

**Comment by jwendell** [comment]
I'd prefer that to cherry-picking a commit that will be included in a few days. Is merging 1.20 HEAD now an issue at all?

**Comment by jewertow** [comment]
> Is merging 1.20 HEAD now an issue at all?

You're right. It's not a problem. We will need to merge tag 1.20.7 to make sure that we are in sync with a particular tag.

So I am closing this PR in favor of https://github.com/maistra/istio/pull/1003.

**Pull request closed without merging**
