### PR TITLE
[2.6] Rebase IOR

### PR DESCRIPTION
**Pull request by yannuil**

### CODE REVIEW

**Comment by jewertow** [comment]
@yannuil please remember about including https://github.com/maistra/istio/pull/980.

**Review by jewertow — COMMENTED** [review]
@yannuil could you please:
1. remove commit "Fix flaky IOR integration test" as it still fails;
2. squash argocd-related commits into "OSSM-6295: Copy all annotations and labels added by ArgoCD except `argocd.argoproj.io/instance`"?

Then I would approve this PR and we could merge it.

**Review by jewertow — COMMENTED** [review]
You forgot about this: https://github.com/maistra/istio/pull/828.

**Review by jewertow — APPROVED** [review]

**Comment by yannuil** [comment]
@jewertow , actually don't need it anymore. The `route` resource is now managed by the upstream informer factory, which has a single method to start all informers.

**Pull request merged**
