### PR TITLE
OSSM-4627 Add option to disable the GatewayClass controller

### PR DESCRIPTION
**Pull request by luksa**

### CODE REVIEW

**Review by jewertow — APPROVED** [review]

**Review by jwendell — COMMENTED** [review]
Have you submitted this upstream first?

**Comment by luksa** [comment]
Upstream PR: https://github.com/istio/istio/pull/46553

**Comment by jewertow** [comment]
@luksa could you cherry-pick this commit to maistra-2.5?

**Comment by luksa** [comment]
@jewertow https://github.com/maistra/istio/pull/834

**Pull request merged**
