### PR TITLE
maistra-1.0: Add POD_NAMESPACE env variable to mixer policy deployment

### PR DESCRIPTION
**Pull request by dgn**
@jwendell fixed this earlier (https://github.com/Maistra/istio/commit/69216323f33f90b63c1d9607e65363aa0ac3aa19) but only for the telemetry deployment.

### CODE REVIEW

**Review by brian-avery — APPROVED** [review]

**Comment by dgn** [comment]
@jwendell do you think this should not go into 1.0.2?

**Comment by jwendell** [comment]
> @jwendell do you think this should not go into 1.0.2?

Sorry, it can get in now. I've put that label to hold the merge until I merged the 1.1.17 code.
Removed the label now.

**Review by jwendell — APPROVED** [review]
LGTM. Did you do the same for 1.1 as well?

**Comment by dgn** [comment]
> > @jwendell do you think this should not go into 1.0.2?
> 
> Sorry, it can get in now. I've put that label to hold the merge until I merged the 1.1.17 code.
> Removed the label now.

Ah, I see- I thought there might be something wrong with it.

> LGTM. Did you do the same for 1.1 as well?

Yup, there's another PR open: ~#57~#60

**Pull request merged**
