### PR TITLE
Do not download envoy-centos image

### PR DESCRIPTION
**Pull request by jwendell**
We do not use it.

Also, change proxy SHA to match maistra proxy.

### CODE REVIEW

**Review by brian-avery — APPROVED** [review]

**Review by dgn — APPROVED** [review]

**Comment by bison** [comment]
This breaks the build for me locally. I can no longer run a simple `make docker` or `make test` without first reverting this. Am I missing something? Is that not the case for everyone else?

**Comment by jwendell** [comment]
@bison You can either run locally: `export ISTIO_ENVOY_BASE_URL=https://storage.googleapis.com/maistra-prow-testing/proxy` before building/testing. Or submit a PR that just changes this. Brian did it as part of [other PR](https://github.com/maistra/istio/pull/240/files#diff-662262a00ad44baa70fb14405b688c43143c3b4635ff8766030dd34b328f8306R124) but it didn't get merged yet.

**Comment by bison** [comment]
That doesn't seem to be enough:

```
~ $ git clone https://github.com/maistra/istio.git
Cloning into 'istio'...
remote: Enumerating objects: 95, done.
remote: Counting objects: 100% (95/95), done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 286555 (delta 24), reused 25 (delta 8), pack-reused 286460
Receiving objects: 100% (286555/286555), 167.72 MiB | 15.50 MiB/s, done.
Resolving deltas: 100% (188867/188867), done.
~ $ cd istio
~/istio $ export ISTIO_ENVOY_BASE_URL=https://storage.googleapis.com/maistra-prow-testing/proxy
~/istio $ git branch
* maistra-2.1
~/istio $ make docker
... lots of output ....
Successfully built 3e92b25c82de
Successfully tagged istio/app_sidecar_centos_8:ca59c341d54c4bb43ff4149928d6e10b80c7396d

real    0m13.971s
user    0m0.052s
sys     0m0.169s
make[1]: *** No rule to make target '/work/out/linux_amd64/envoy-centos', needed by '/work/out/linux_amd64/release/istio-sidecar-centos-7.rpm'.  Stop.
make: *** [Makefile.overrides.mk:29: docker] Error 2
```

**Comment by jwendell** [comment]
We don't rely or use make docker. You should use our images in istio-centos-images repo.

**Comment by bison** [comment]
Okay. Even so, it seems preferable to not break basic parts of the upstream build / dev workflow here.

What was the original reason for this? I can't tell from the PR description.

**Comment by jwendell** [comment]
We don't build a separate `envoy-centos` like upstream. So our prow tests (which end up running the `init` make target) failed because of that.

Another solution for this would be copying our generated `envoy.tar` to `envoy-centos.tar` in our proxy builds, and revert this `bin/init.sh` changes. Thus it would find the file. I will try that.

**Comment by bison** [comment]
Cool. Thanks! Let me know if you want me to test.

**Pull request merged**
