### PR TITLE
Add MemberRoll controller

### PR DESCRIPTION
**Pull request by bison**
Cherry-pick for 1.6.0 rebase including the following:

### Changes to MultiListerWatcher required for multi-tenancy
    
Squashed commit, incorporates changes from:
    
  * MAISTRA-417: Changes required for dynamic namespace support in
    multi-tenancy
    
  * MAISTRA-422: Return meaningful resource versions from
    multiListWatcher
    
  * MAISTRA-434: Fix panic with sending to result on stop
  
  * MAISTRA-448: Switch reportUpdatedNamespaceError monitoring to
    stopped channel and add to wait group
    
  * MAISTRA-452: Force an error if an underlying result channel closes
   silently
    
  * MAISTRA-862 Prevent deadlock in case of Watch() errors in
    subsequent List()

### Add MemberRollController
    
Squashed commit, consisting of:
    
  * MAISTRA-417: Add MemberRollController
    
  * MAISTRA-450: Switch across to ConfiguredMembers and check existing
    config for changes
    
  * MAISTRA-1005 Do not expect namespaces to have a stable ordering

### CODE REVIEW

**Comment by bison** [comment]
The build was broken because the clients needed to be regenerated. Upstream client generation tasks live in the `istio/client-go` repo, so I adapted that and added a Makefile with Maistra specific client generation bits here.

**Review by dgn — APPROVED** [review]

**Comment by dgn** [comment]
Removed the `okay to merge` label for now, I'm running integration tests

**Comment by dgn** [comment]
Nevermind, my docker setup is broken...

**Review by dgn — CHANGES_REQUESTED** [review]
I'm afraid this breaks the integration tests:

```
2020-06-03T15:21:35.829721Z	error	pkg/mod/k8s.io/client-go@v0.18.0/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: resourceVersion: Invalid value: "=3475": strconv.ParseUint: parsing "=3475": invalid syntax
2020-06-03T15:21:39.342250Z	error	pkg/mod/k8s.io/client-go@v0.18.0/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: resourceVersion: Invalid value: "=2598": strconv.ParseUint: parsing "=2598": invalid syntax
2020-06-03T15:21:39.826738Z	error	pkg/mod/k8s.io/client-go@v0.18.0/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: resourceVersion: Invalid value: "=3475": strconv.ParseUint: parsing "=3475": invalid syntax
2020-06-03T15:21:39.839726Z	error	pkg/mod/k8s.io/client-go@v0.18.0/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: resourceVersion: Invalid value: "=2592": strconv.ParseUint: parsing "=2592": invalid syntax
2020-06-03T15:21:41.044240Z	error	pkg/mod/k8s.io/client-go@v0.18.0/tools/cache/reflector.go:125: Failed to list *v1.Service: resourceVersion: Invalid value: "=3373": strconv.ParseUint: parsing "=3373": invalid syntax
2020-06-03T15:21:42.491986Z	error	pkg/mod/k8s.io/client-go@v0.18.0/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: resourceVersion: Invalid value: "=2592": strconv.ParseUint: parsing "=2592": invalid syntax
2020-06-03T15:21:42.642285Z	error	pkg/mod/k8s.io/client-go@v0.18.0/tools/cache/reflector.go:125: Failed to list *v1.ConfigMap: resourceVersion: Invalid value: "=4936": strconv.ParseUint: parsing "=4936": invalid syntax
2020-06-03T15:21:43.664466Z	error	pkg/mod/k8s.io/client-go@v0.18.0/tools/cache/reflector.go:125: Failed to list *v1.Service: resourceVersion: Invalid value: "=3373": strconv.ParseUint: parsing "=3373": invalid syntax
2020-06-03T15:21:45.475750Z	error	pkg/mod/k8s.io/client-go@v0.18.0/tools/cache/reflector.go:125: Failed to list *v1.ConfigMap: resourceVersion: Invalid value: "=4936": strconv.ParseUint: parsing "=4936": invalid syntax
2020-06-03T15:21:45.476920Z	error	pkg/mod/k8s.io/client-go@v0.18.0/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: resourceVersion: Invalid value: "=2282": strconv.ParseUint: parsing "=2282": invalid syntax
2020-06-03T15:21:46.488890Z	error	pkg/mod/k8s.io/client-go@v0.18.0/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: resourceVersion: Invalid value: "=2592": strconv.ParseUint: parsing "=2592": invalid syntax
2020-06-03T15:21:47.270299Z	error	pkg/mod/k8s.io/client-go@v0.18.0/tools/cache/reflector.go:125: Failed to list *v1.Service: resourceVersion: Invalid value: "=3373": strconv.ParseUint: parsing "=3373": invalid syntax
```

**Comment by bison** [comment]
@dgn, yep that's the issue I mentioned with the resource version getting passed to `List()`. Guess I can try to get a fix for that in here as well.

**Comment by bison** [comment]
Added 21b7c12 to work around the problems with re-lists failing -- this became a problem with a recent Kubernetes client update. Just waiting on integration tests.

**Comment by bison** [comment]
So, in fighting with this over the last week I think it's become clear that we can't continue to return events from the `MutliListWatcher` with modified `ResourceVersions` fields. I've kept the parts that modify it during the initial `List()` call, so that we can try to parse that in `Watch()` and distribute those to the underlying watches, but I've removed the bits that then modified `ResourceVersion` before sending events to the results channel.

This is passing unit and integration tests for me locally.

**Review by dgn — APPROVED** [review]
as mentioned in chat, I think this is alright to unblock us. we should monitor whether this hurts performance, though

**Review by dgn — COMMENTED** [review]
~I'm still seeing errors that look legitimate in the integration tests:~

Nevermind I realized this was my environment

**Comment by bison** [comment]
Weird. It's passing for me. I'll double check though.

**Comment by dgn** [comment]
This might have been a blip in my env. Let's get this merged, we can still catch problems later on

**Comment by bison** [comment]
Merged manually after some off-line discussion. No reason to require two separate reviews on these for now.

**Pull request merged**
