### PR TITLE
OSSM-2193 cherry-picked to 2.2

### PR DESCRIPTION
**Pull request by luksa**
I had to make one additional change (see first commit) for the cherry-picks to apply cleanly.

### CODE REVIEW

**Review by dgn — APPROVED** [review]

**Comment by dgn** [comment]
Strange, the 2.3 jobs seem to have been run against this PR?

**Comment by jwendell** [comment]
> Strange, the 2.3 jobs seem to have been run against this PR?

Because he targeted the wrong branch initially.

**Pull request merged**
