### PR TITLE
MAISTRA-2439: Prevent federation from exporting services that are not visible to the federation gateway

### PR DESCRIPTION
**Pull request by jwendell**
By taking into consideration the service annotation
`networking.istio.io/exportTo`.

This annotation restricts where this service is visible: https://istio.io/latest/docs/reference/config/annotations/

If a service is not reachable from the federation gateway namespace due
to this annotation, it should not be exported.

### CODE REVIEW

**Review by dgn — APPROVED** [review]
thanks Jonh, looks good. Should we create an OSSMDOCS issue to make sure this is documented?

**Comment by jwendell** [comment]
@dgn I'm not sure. Talking to @rcernich he said this would be the expected behavior. I mean, it's expected that users would understand this service would not be exported once they add such annotations.

That said, I think documentation is always good to have, even if "in obvious cases", right?

**Review by rcernich — APPROVED** [review]

**Comment by dgn** [comment]
> @dgn I'm not sure. Talking to @rcernich he said this would be the expected behavior. I mean, it's expected that users would understand this service would not be exported once they add such annotations.
> 
> That said, I think documentation is always good to have, even if "in obvious cases", right?

+1 I think it doesn't hurt creating the ticket, albeit with maybe lower Priority. If we don't get to writing that part, so be it

**Pull request merged**
