### PR TITLE
MAISTRA-2269: Increase hardcoded QPS/Burst to a more reasonable limit

### PR DESCRIPTION
**Pull request by knrc**
Increase QPS/Burst to a more reasonable limit

### CODE REVIEW

**Comment by luksa** [comment]
How were these numbers determined? They seem somewhat high. In OpenShift, the default QPS/burst for the kubelet is 50/100, so you get 2000/4000 only in 40-node clusters. Wouldn't something like 250/500 be a more reasonable default?

**Comment by knrc** [comment]
> How were these numbers determined? They seem somewhat high. In OpenShift, the default QPS/burst for the kubelet is 50/100, so you get 2000/4000 only in 40-node clusters. Wouldn't something like 250/500 be a more reasonable default?

I tried with 1000/2000 and was seeing throttling in the order of seconds, increasing this to 2000/4000 brought the throttling down to microseconds/nanoseconds.  This was for a 500 namespace test.

As per the JIRA this is just a temporary change until we get a more comprehensive solution in a later release

**Comment by jwendell** [comment]
Does this have some side effect? In other words, why OpenShift values are so low if they can be increased without worries?

**Comment by knrc** [comment]
> Does this have some side effect? In other words, why OpenShift values are so low if they can be increased without worries?

It will put more load on the API server for a short period of time, the tradeoff for customers who need this is a more responsive service mesh and available applications.  With the original defaults we were seeing throttling delaying requests for 4 minutes and longer.

Normal clients do not need to perform the type of intensive API server access we are doing within istiod/pilot.

**Comment by luksa** [comment]
> Does this have some side effect? In other words, why OpenShift values are so low if they can be increased without worries?

The default values that OpenShift uses for the kubelet suffice when running a limited number of pods on each node. Users are encouraged to increase these values if required, but this does cause a higher load on the API server. 

I'd say these settings depend highly on the cluster, so it's hard to know what the appropriate values are. I'm concerned that too high values could affect the other components running in the cluster. But I don't really know what would be considered a high value. If Pilot needs values this high for normal operation, then we may just need to use them and require users to beef up their API servers. 

My gut feeling is that 2000/4000 is too high, but I can't back it up. I'd feel much better with lower values and instructing users who run 100+ namespaces to increase them in the config.

**Comment by knrc** [comment]
> My gut feeling is that 2000/4000 is too high, but I can't back it up. I'd feel much better with lower values and instructing users who run 100+ namespaces to increase them in the config.

What values would you suggest?  I can rerun the test with those to see the impact.  Our current issue is that we have no way of configuring these in any config, I've opened another issue to deal with this but in the meantime we need to set the defaults to a more reasonable value.

**Comment by luksa** [comment]
> What values would you suggest? I can rerun the test with those to see the impact. Our current issue is that we have no way of configuring these in any config, I've opened another issue to deal with this but in the meantime we need to set the defaults to a more reasonable value.

I'd feel okay with 250/500, which is the equivalent of 5 kubelets/nodes. Or maybe keep the QPS relatively low and just increase the Burst to ensure that Pilot can do what it needs without being blocked. IIRC you mentioned we need 2000/4000 for _500 namespaces_.  That doesn't sound like a typical scenario, so if we reduce the QPS to several hundred, we would still support around 100 namespaces which should be more than enough for most users (?).

**Comment by knrc** [comment]
> I'd feel okay with 250/500, which is the equivalent of 5 kubelets/nodes. Or maybe keep the QPS relatively low and just increase the Burst to ensure that Pilot can do what it needs without being blocked.

okay, I can try that and see how it looks although with 1000/2000 it was still showing significant throttling.

> IIRC you mentioned we need 2000/4000 for _500 namespaces_. That doesn't sound like a typical scenario, so if we reduce the QPS to several hundred, we would still support around 100 namespaces which should be more than enough for most users (?).

Not usual, however it does happen and we have customers who are deploying meshes with around 300 namespaces.

**Comment by jwendell** [comment]
> Not usual, however it does happen and we have customers who are deploying meshes with around 300 namespaces.

This is awesome. I'm guessing upstream doesn't have customers doing this, therefore they never had encountered this issue. This is worth to raise upstream and backport this PR and discuss there as well, so that we don't have to carry this on with us forever.

**Comment by knrc** [comment]
> okay, I can try that and see how it looks although with 1000/2000 it was still showing significant throttling.

Not so good with those figures, we have 6825 requests (out of 13382 requests) which are being throttled by > 1s with everything ramping up until we hit 10s throttles per requests.

**Comment by brian-avery** [comment]
Google customers are running some pretty large meshes. Not sure how many namespaces they have though.

**Comment by knrc** [comment]
After discussing with @luksa and others we settled on defaults of 500 for QPS and 1000 for Burst but with the addition of environment variables should this need to be overridden

**Review by luksa — APPROVED** [review]

**Review by jwendell — COMMENTED** [review]
Why not put them in the already existing `pilot/pkg/features/pilot.go` file?

**Comment by knrc** [comment]
> Why not put them in the already existing `pilot/pkg/features/pilot.go` file?

Good idea, will do that

**Comment by knrc** [comment]
> > Why not put them in the already existing `pilot/pkg/features/pilot.go` file?
> 
> Good idea, will do that

should be done

**Review by jwendell — APPROVED** [review]

**Comment by dgn** [comment]
> > Not usual, however it does happen and we have customers who are deploying meshes with around 300 namespaces.
> 
> This is awesome. I'm guessing upstream doesn't have customers doing this, therefore they never had encountered this issue. This is worth to raise upstream and backport this PR and discuss there as well, so that we don't have to carry this on with us forever.

No, they do have very large customers, but they don't use multi-tenancy so they don't have the same problem. We have to send 1 request per namespace per resource; they watch globally so they only send 1 request per resource

**Pull request merged**
