### PR TITLE
[maistra-2.6] Rebase building OpenSSL-based proxy image

### PR DESCRIPTION
**Pull request by yxun**
* OSSM-2378: Use Maistra proxy CentOS Stream 8 img (#713)

* OSSM-2378: Use Maistra proxy CentOS Stream 8 img

For integration tests. Based on (#609)

* Build container images with docker

* Use maistra proxy and CentOS Stream 8 as a base image for proxyv2

* Test VMs using CentOS Stream 8

* Temporarily skip failing security tests

* Temporarily skip tests suite telemetry.prometheus.wasm

* fix(tests): enables fixed integration tests

* Use our proxy (#801)

* OSSM-5958: Remove wasm extensions (#937)

* Do not rely on WASM extensions

Since https://github.com/maistra/proxy/pull/253

* Remove wasm extensions from EnvoyFilters

* Disable tests for WASM extensions

* Remove commented code

---------

* Disable failing tests

* Fix TestTrustDomainValidation - change expected TLS error to make it work with OpenSSL

---------

**Please provide a description of this PR:**

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Comment by yxun** [comment]
We skipped some integration tests in the previous 2.5 proxy image rebase PR.
When we have a 2.6 maistra proxy build, we can re-enable the skipped tests.

**Comment by yxun** [comment]
Use 2.5 proxy binary SHA until having a 2.6 proxy build.
When we have a 2.6 proxy build, need to update the Dockerfile.proxyv2 base image from centos:stream8 to centos:stream9

**Comment by yxun** [comment]
Use 2.5 proxy binary SHA until having a 2.6 proxy build.
When we have a 2.6 proxy build, need to update the Dockerfile.proxyv2 base image from centos:stream8 to centos:stream9

**Comment by jwendell** [comment]
Closing in favor of https://github.com/maistra/istio/pull/1048

**Pull request closed without merging**
