### PR TITLE
MAISTRA-2566 migrate controllers CRD version to v1 from v1beta1

### PR DESCRIPTION
**Pull request by rcernich**
Signed-off-by: rcernich <rcernich@redhat.com>

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by rcernich** [comment]
This is ready for review.

**Review by jwendell — APPROVED** [review]

**Comment by dgn** [comment]
Are these changes required? I thought we'd disabled all CRD reading

**Comment by rcernich** [comment]
I'm not certain.  If istiod no longer has permission to read CRDs, then I don't think this is necessary.  I didn't migrate the operator code at all, as it's not used by us.

**Comment by rcernich** [comment]
We're not using any of the code affected by these changes.

**Pull request closed without merging**
