### PR TITLE
MAISTRA-2131: ior: honor Gateway's httpsRedirect

### PR DESCRIPTION
**Pull request by jwendell**
If Gateway's `httpsRedirect` is set to true, create the OpenShift Route
with Insecure Policy set to `Redirect`.

### CODE REVIEW

**Review by dgn — APPROVED** [review]
good opportunity to add unit tests maybe?

**Comment by jwendell** [comment]
@dgn I'm afraid adding them is a little bit more complex than fixing this issue. So, worth doing it in a separate PR.

See https://issues.redhat.com/browse/MAISTRA-1813

**Review by rcernich — APPROVED** [review]

**Review by brian-avery — APPROVED** [review]

**Pull request merged**
